### PR TITLE
MVBE-2271-imapclient-extentions

### PR DESCRIPTION
**Pull request by switch87**
https://vikingco.atlassian.net/browse/MVBE-2990
Bugfix for using pytest.
IMAPclient-extentions did an install of distribute, a deprecated fork of setuptools.
by removing the installation scripts IMAPclient-extentions seems to install normally and pytest keeps working.

### CODE REVIEW

**Comment by pieterdd** [comment]
@kristofclaes This PR hasn't been picked up for review yet. Only thing I can think of doing is checking if setup.py ran successfully in my dev env.

**Comment by pieterdd** [comment]
No time to review right now, got too much bugs under my wings currently.

**Comment by pieterdd** [comment]
Added parent pull request in MVNE. If this builds successfully, this can be shipped.

**Comment by switch87** [comment]
I used it 3 or 4 weeks in tox and circleci, it is the fix that was needed to make pytest work.

**Pull request merged**
